underlay_interfaces:
  - { interface: ge-0/0/0, ip: "192.168.1.2", mask: "/30", peer: "Spine1" }
  - { interface: ge-0/0/1, ip: "192.168.1.14", mask: "/30", peer: "Spine2" }

loopback_ip: "10.10.10.3/32"
ospf_area: "0.0.0.0"
