- name: Deploy EVPN/VXLAN Configuration
  junipernetworks.junos.junos_config:
    lines:
      - set vlans VNI_100 l3-interface irb.50
      - set vlans VNI_100 l3-interface irb.60
      - set interfaces irb unit 50 proxy-macip-advertisement
      - set interfaces irb unit 50 virtual-gateway-accept-data
      - set interfaces irb unit 50 family inet address 192.168.50.1/24 preferred
      - set interfaces irb unit 50 family inet address 192.168.50.1/24 virtual-gateway-address 192.168.50.254
      - set interfaces irb unit 60 proxy-macip-advertisement
      - set interfaces irb unit 60 virtual-gateway-accept-data
      - set interfaces irb unit 60 family inet address 192.168.60.1/24 preferred
      - set interfaces irb unit 60 family inet address 192.168.60.1/24 virtual-gateway-address 192.168.60.254
    comment: install the vxlan l3 tunnel

- name: Check Commit
  junipernetworks.junos.junos_config:
    check_commit: true

- name: Commit the new configuration
  junipernetworks.junos.junos_config:
    confirm_commit: true

- name: Backup the configuration
  junipernetworks.junos.junos_config:
    backup: true
    backup_options:
      filename: backup_{{ inventory_hostname }}.cfg
      dir_path: /home/win/juniperbackup